export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_FISCAL_YEARS_SUCCESS = 'LOAD_FISCAL_YEARS_SUCCESS';
export const LOAD_JOBS_SUCCESS = 'LOAD_JOBS_SUCCESS';

export const CREATE_UPDATE_STANDARD_ITEM_SUCCESS = 'CREATE_UPDATE_STANDARD_ITEM_SUCCESS';
export const UPDATE_STANDARD_ITEM_SUCCESS = 'UPDATE_STANDARD_ITEM_SUCCESS'
export const LOAD_STANDARD_ITEMS__SUCCESS = 'LOAD_STANDARD_ITEMS__SUCCESS';
export const LOAD_STANDARD_ITEM_CHECKPOINT_TYPES__SUCCESS = 'LOAD_STANDARD_ITEM_CHECKPOINT_TYPES__SUCCESS';

export const LOAD_SHOPSUBS_SUCCESS = 'LOAD_SHOPSUBS_SUCCESS';

export const LOAD_TICKETS_SUCCESS = 'LOAD_TICKETS_SUCCESS';
export const CREATE_UPDATE_TICKET_SUCCESS = 'CREATE_UPDATE_TICKET_SUCCESS';
export const LOAD_TICKET_CHECKPOINT_TYPES__SUCCESS = 'LOAD_TICKET_CHECKPOINT_TYPES__SUCCESS';

export const LOAD_CHECKPOINTS_SUCCESS = 'LOAD_CHECKPOINTS_SUCCESS';
export const LOAD_CHECKPOINTRESULTS_SUCCESS = 'LOAD_CHECKPOINTRESULTS_SUCCESS';
export const CREATE_UPDATE_CHECKPOINT_SUCCESS = 'CREATE_UPDATE_CHECKPOINT_SUCCESS';

